config/routes.rb
Rails.application.routes.draw do
  root "records#new"

  resources :records
  get "/records", to: "records#index"
  get "collage", to: "records#collage"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
require 'rmagick'
require 'securerandom'
class Record < ApplicationRecord
  def self.get_lastfm_data(params)
    if params[:record][:username].blank? || params[:record][:months].blank? || params[:record][:data_type].blank?
      return nil
    end
    return nil if !["7day", "1month", "3month", "6month", "12month"].include?(params[:record][:months])
    return nil if !["3x3", "4x4", "5x5"].include?(params[:record][:data_type])

    username = params[:record][:username]
    months = params[:record][:months]
    data_type = params[:record][:data_type]
    start_date = Record.get_start_date(params)

    user_data = (Net::HTTP.get_response(URI("https://ws.audioscrobbler.com/2.0/?method=user.getTopAlbums&user=#{username}&period=#{months}&api_key=#{RecordsController::LAST_FM_API_KEY}&format=json")))
    if user_data.code == "404"
      return nil
    end

    res = JSON.parse(user_data.body)
    case data_type
    when "3x3"
      total_records = 9
      canvas_width = 900
      canvas_height = 900
      image_width = 300
      image_height = 300
      columns = 3
    when "4x4"
      total_records = 16
      canvas_width = 1200
      canvas_height = 1200
      image_width = 300
      image_height = 300
      columns = 4
    when "5x5"
      total_records = 25
      canvas_width = 1500
      canvas_height = 1500
      image_width = 300
      image_height = 300
      columns = 5
    end

    image_paths = []
    random_string = SecureRandom.random_number(1_000_000_000).to_s.rjust(10, '0')

    res["topalbums"]["album"].first(total_records).each do |a|
      images_array = a["image"]
      extra_large_image_url = images_array[3]["#text"]
      image_paths << extra_large_image_url
    end
    canvas = Magick::Image.new(canvas_width, canvas_width) do |c|
      c.background_color = 'white'
    end

    image_paths.reject!(&:empty?)

    image_paths.each_with_index do |image_url, index|
      image = Magick::Image.read(image_url).first
      image.resize_to_fill!(image_width, image_height)
      row = index / columns
      col = index % columns
      canvas.composite!(image, col * image_width, row * image_height, Magick::OverCompositeOp)
    end

    canvas.write(Rails.root.join('public', 'collages', "output_collage#{random_string}.jpg"))
    {random_string: random_string, start_date: start_date, username: username}
  end

  def self.get_start_date(params)
    (params[:record][:months] == "7day") ? (Date.today - 7.days) : (Date.today - (params[:record][:months]).to_i.months)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  require 'net/http'

  LAST_FM_API_KEY = ENV['LAST_FM_API_KEY']
     
  def new
    Record.destroy_all
  end

  def create
    start_date = Record.get_start_date(params)
    data = Record.get_lastfm_data(params)

    if data.blank?
      redirect_to root_path, notice: "No Last.Fm users with the usersname '#{params[:record][:username]}' were found, please try again." and return
      @record.destroy!
    end

    redirect_to collage_path(data: data)
  end

  def collage
    @end_string = "for #{params[:data][:username]} from #{params[:data][:start_date].to_date.to_formatted_s(:long_ordinal)} until now"
    @data = params[:data][:random_string]
    puts("data: #{@data}")
    render template: "records/albums"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastFmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
        <p class="flash-message">
          <%= msg %>
        </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/records/albums.html.erb
<h1><b>These are the top albums <%= @end_string %>!</b></h1>
<div class="data-div">
  <%= image_tag("/collages/output_collage#{@data}.jpg") %>
</div>
<br><a href="/records/new" class="button">Make a new one!</a>

app/views/records/artists.html.erb
<h1><b>These are the top artists <%= @end_string %>!</b></h1>
<div class="data-div">
  <% @data.each do |a| %>
    <%= image_tag("#{a[:image]}", class: 'custom-image') %>
    <p> <%= a[:name] %>: <%= a[:playcount] %> scrobbles </p>
  <% end %>
</div>
<br><a href="/records/new" class="text-box">Make a new one!</a>

app/views/records/index.html.erb
<h1>Hello! Welcome to Last.Fm Records Views</h1> 
<a href="/records/new" class="button">Start a new one</a>
<table>
  <tr>
    <th>Username</th>
  </tr>

  <% @records.each do |record| %>
    <tr>
      <td><a href="/records/<%= record.id %>" class="button">Show</a></td>
      <td><%= record.username %></td>
    </tr>
  <% end %>
</table>

app/views/records/new.html.erb
<div>
<h1 id="new-title"> We want to find your listening history for the past month! </h1>
</div>
<%= form_with scope: :record, url: records_path, id: "record_form", local: true do |f| %>
  <p>
  <%= f.label :username %>
  <%= f.text_field :username, class: "text-box" %>
  </p>

  <p>
    <%= f.select :months, [["7 days", "7day"], ["1 month", "1month"], ["3 months", "3month"], ["6 months", "6month"], ["One year", "12month"]] %>
  </p>

  <p>
    <%= f.select :data_type, [["3x3", "3x3"], ["4x4", "4x4"], ["5x5", "5x5"]] %>
  </p>

  <p>
    <%= f.submit "Let's Go!", class: "submit-button"%>
  </p>
<% end %>

<div class="custom-loader" id="circles-loading""></div>

<script>
  const recordForm = document.getElementById('record_form');
  const usernameBox = document.getElementById('record_username');
  const loader = document.getElementById('circles-loading');
  recordForm.addEventListener("submit", formSubmit);

  function formSubmit(event) {
    if (usernameBox.value == "") {
      event.preventDefault();
      alert("Please enter a username");
    }else{
      recordForm.style.display = "none";
      document.getElementById('new-title').style.display = "none";
      loader.style.display = "block";
    }
  }
</script>

app/views/records/songs.html.erb
<h1><b>These are the top songs <%= @end_string %>!</b></h1>
<div class="data-div">
  <% @data.each do |a| %>
    <p> <%= a[:song_name] %> by <%= a[:artist_name] %>: <%= a[:playcount] %> scrobbles </p>
  <% end %>
</div>
<br><a href="/records/new" class="text-box">Make a new one!</a>